assigned empty value to subtitle_stream
otherwise the script crashes if a video doesn't have subtitles, for example:
>>Succesfully logged in
>>Traceback (most recent call last):
>>  File "main.py", line 120, in <module>
>>    stream_url = account.m3u8_stream(video_link[0])
>>  File "/drives/d/DATA/PortableApps/WWE-Network-Downloader-master/wwe.py", line 68, in m3u8_stream
>>    return stream['hls']['url'], subtitle_stream
>>UnboundLocalError: local variable 'subtitle_stream' referenced before assignment